### PR TITLE
feat: add payment table pagination

### PR DESCRIPTION
**Pull request by musayann**

### CODE REVIEW

**Comment by bumi** [comment]
didn't we already have pagination? what is this doing?
image

**Comment by musayann** [comment]
> didn't we already have pagination? what is this doing? image

it wasn't paginated on the database side, it was just the on the soft side. not sure if keeping that implementation would be a great approach

**Comment by bumi** [comment]
ah sure. with your update wordpress uses the server pagination automatically?

**Comment by musayann** [comment]
> ah sure. with your update wordpress uses the server pagination automatically?

Yes, sure. now it won't have to load many records at once. will just retrieve the ones that will be displayed on a page

**Pull request merged**
